version: '2'

services:

  app:
    build: .
    # image: ghcr.io/codions/revive-adserver/revive-adserver:latest
    container_name: app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - ENABLE_SUPERVISOR_GUI=true
      - SUPERVISORD_USER=admin
      - SUPERVISORD_PASS=secret

    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/storage/app/www/images:/usr/share/nginx/html/www/images

    ports:
      - "8080:80"
      - "9001:9001"
    links:
      - mysql
      - mailcatcher

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=revive
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./.docker/storage/mysql:/var/lib/mysql

  mailcatcher:
    image: codions/mailcatcher
    container_name: mailcatcher
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "1080:1080"