version: '2'

services:
  app:
    platform: linux/amd64  # ✅ 指定平台，避免 arm64 問題
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - mailpit

    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/storage/app/www/images:/usr/share/nginx/html/www/images

    ports:
      - "80:80"  # ✅ Zeabur 預設監聽 80

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    links:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    platform: linux/amd64
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
