version: '3.2'
services:
  app:
    build: .
    container_name: app
    ports:
        - '8080:80'
    restart: unless-stopped
    depends_on:
        - mysql
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: revive
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./.docker/storage/mysql:/var/lib/mysql