version: '2'

services:

  app:
    build: .
    # image: ghcr.io/codions/revive-adserver/revive-adserver:latest
    restart: unless-stopped
    depends_on:
      - mysql

    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/storage/app/www/images:/usr/share/nginx/html/www/images

    ports:
      - "8080:80"
    links:
      - mysql
      - mailpit

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=revive
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./.docker/storage/mysql:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'